### ISSUE TITLE
[BUG] Detector Equip Slot

### ISSUE THREAD

**Issue by NoodlersS** [HyperGaming-Network/hgn-srp-server#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Bear and Echo detectors, and presumably the Veles detector too ,all occupy equip slot [1] which is where the primary weapon is placed.

Depending on the order of equipping it, either the detector or the primary weapon is available on the scroll wheel.

This can easily be fixed by putting it to equip slot 4 which is classified as None which looked to be an unused slot.

### Expected Behavior

It should be not blocking your primary from use or vice versa

### Steps To Reproduce

1. be on server
2. equip a primary and a detector
3. observe by trying to swap sweps
4. see the problem

**Comment by Ireheart** [comment]
Was done by picto
