### ISSUE TITLE
[BUG] Flashlight "check battery" script error

### ISSUE THREAD

**Issue by Terrafryer** [HyperGaming-Network/hgn-srp-server#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click on "check battery", it currently gives me a script error, listed below.

[ERROR] gamemodes/helix/gamemode/core/libs/sh_notice.lua:113: invalid option '%' to 'format'
  1. L - [C]:-1
   2. NotifyLocalized - gamemodes/helix/gamemode/core/libs/sh_notice.lua:113
    3. func - gamemodes/helix/gamemode/core/libs/sh_notice.lua:162
     4. unknown - lua/includes/extensions/net.lua:33

### Expected Behavior

Originally, it would show up the battery's percentage life. Now, it does not.

### Steps To Reproduce

1. Place in a battery into the flashlight.
2. Click on "check battery"

**Comment by ShaunBoughey** [comment]
Resolved and live on the server.
