### ISSUE TITLE
[BUG] Inappropiate Suit Models

### ISSUE THREAD

**Issue by Madcombat** [HyperGaming-Network/hgn-srp-server#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Wrong suit item paths.  Example
Green anorak = Sunrise suit.

### Expected Behavior

Correct suit item paths.  Example
Green anorak = Green Anorak

### Steps To Reproduce

Step 1. Buy Fucked up Suit
Step 2. Equip fucked up Suit
Step 3. Dont blink

### Anything else?

:)

**Comment by longlostblake** [comment]
@pictowolf 
To fix this we would need to have bodygroup detection in the armor base. I could throw a few more models out as items too this way.

**Comment by ShaunBoughey** [comment]
@longlostblake it's already doable. Utilise the folllowing:

ITEM.newSkin = 5
ITEM.bodyGroups = {
	["blade"] = 1,
	["bladeblur"] = 1
}

Happy to do a few exmaples as needed.
